### ISSUE TITLE
 ERROR: Bytecode HARs: [@candies/image_cropper, @candies/image_editor] not supported when useNormalizedOHMUrl is not true.

### ISSUE THREAD

**Issue by jialinghui** [HarmonyCandies/image_cropper#1]
> hvigor ERROR: Bytecode HARs: [@candies/image_cropper, @candies/image_editor] not supported when useNormalizedOHMUrl is not true.

DevEco Studio NEXT Release 5.0.3.900
OpenHarmony/Sdk API12 v5.0.0.71

**Comment by zmtzawqlp** [comment]
进群问吧？ 貌似app 要配置 useNormalizedOHMUrl

**Comment by zmtzawqlp** [comment]
qq 群 981630644

**Comment by zmtzawqlp** [comment]
![2f2fd1e276d4f919300ecf78ca788aff](https://github.com/user-attachments/assets/92ef816b-adb3-4795-a56b-7f63c5c6dc70)

**Comment by zmtzawqlp** [comment]
解决了吗？

**Comment by jialinghui** [comment]
> 找到了吗？

![image](https://github.com/user-attachments/assets/9ce29880-aabc-44cd-84b8-422b274666de)
yes
