### ISSUE TITLE
能否在拉伸或缩放剪裁区域的时候，原图不动？

### ISSUE THREAD

**Issue by qq2026ai** [HarmonyCandies/image_cropper#6]
现状:

设定一个比例剪裁后，每当缩放剪裁框，原图就会放大，导致我又要缩放原图（缩放原图过程有时还不灵活）

期望：

有一个参数可以控制，只可以改变剪裁框的大小，不修改原图的缩放比例

**Comment by zmtzawqlp** [comment]
居中。是每个相册 app 必做的事情

**Comment by zmtzawqlp** [comment]
你先玩玩安卓和ios 的相册
